#!/usr/bin/env bash
# Regenerate the auto-generated tree index for the Mythic skill.
#
# This is the "grows with the code" hook: run it whenever the file tree changes
# (new build/* component, new *_ios.c fork, new bridge file) so the knowledge
# base's structural index stays accurate without hand-editing.
#
# Output: references/_autogen-tree.md (relative to this script's dir).
#
# Safe to run from anywhere; it does not modify source files.
set -eu

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$SKILL_DIR/../../.." && pwd)"
OUT="$SKILL_DIR/references/_autogen-tree.md"

# List files under REPO_ROOT/$1 as repo-relative paths, skipping hidden entries
# and (for the app dir) large bundled artifacts.
tree_of() {
  find "$REPO_ROOT/$1" -type f \
    ! -path '*/.*' \
    ! -name '*.a' ! -name '*.pem' ! -name '*.gz' ! -name '*.tgz' \
    2>/dev/null | sed "s#^$REPO_ROOT/##" | sort
}

{
  echo "<!-- AUTO-GENERATED by scripts/refresh.sh — DO NOT EDIT BY HAND. -->"
  echo "# Live tree index"
  echo
  echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo

  echo "## iOS app sources (app/Mythic)"
  echo '```'
  tree_of app/Mythic
  echo '```'
  echo

  echo "## Build components (build/)"
  echo '```'
  tree_of build
  echo '```'
  echo

  echo "## ntdll-unix iOS forks"
  echo '```'
  tree_of build/ntdll-unix | grep -E '_ios\.(c|h)$'
  echo '```'
  echo

  echo "## Scripts"
  echo '```'
  tree_of scripts
  echo '```'
} > "$OUT"

echo "Wrote $OUT"
wc -l < "$OUT" | awk '{print "  (" $1 " lines)"}'
